# Generated by Django 4.1.4 on 2023-01-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="toDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        db_index=True, help_text="The task to be done", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compleated",
                    models.BooleanField(
                        default=False, help_text="The Status of the Task"
                    ),
                ),
            ],
            options={"verbose_name": "Todo List", "verbose_name_plural": "Todo Lists",},
        ),
    ]
