# Generated by Django 4.1.4 on 2023-01-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toDo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "Todo List", "verbose_name_plural": "Todo Lists"},
        ),
        migrations.RemoveField(model_name="todo", name="compleated_at",),
        migrations.AddField(
            model_name="todo",
            name="compleated",
            field=models.BooleanField(default=False),
        ),
    ]
